version: "3.9"

services:
  ml-backend:
    restart: unless-stopped
    build: ./backend/
    ports:
      - "9004:9000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  st-frontend:
    restart: unless-stopped
    build: ./frontend/
    ports:
      - "9007:9000"
    environment:
      - ML_ENDPOINT=${ML_ENDPOINT}
