version: "3.9"

services:
  api:
    restart: unless-stopped
    build: ./api/
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    network_mode: "host"

  frontend:
    restart: unless-stopped
    build: ./frontend/
    network_mode: "host"
